const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),WebSocket=require('ws');
const telegram=require('./telegram-bot');
const PORT=process.env.PORT||3000,PUBLIC=path.join(__dirname,'public'),rooms=new Map(),RECONNECT_MS=120000;
const HEROES=["Abaddon","Alchemist","Ancient Apparition","Anti-Mage","Arc Warden","Axe","Bane","Batrider","Beastmaster","Bloodseeker","Bounty Hunter","Brewmaster","Bristleback","Broodmother","Centaur Warrunner","Chaos Knight","Chen","Clinkz","Clockwerk","Crystal Maiden","Dark Seer","Dark Willow","Dawnbreaker","Dazzle","Death Prophet","Disruptor","Doom","Dragon Knight","Drow Ranger","Earthshaker","Earth Spirit","Elder Titan","Ember Spirit","Enchantress","Enigma","Faceless Void","Grimstroke","Gyrocopter","Hoodwink","Huskar","Invoker","Jakiro","Juggernaut","Keeper of the Light","Kez","Kunkka","Legion Commander","Leshrac","Lich","Lifestealer","Lina","Lion","Lone Druid","Luna","Lycan","Marci","Magnus","Mars","Medusa","Meepo","Mirana","Monkey King","Morphling","Muerta","Naga Siren","Nature's Prophet","Necrophos","Night Stalker","Nyx Assassin","Ogre Magi","Omniknight","Oracle","Outworld Destroyer","Pangolier","Phantom Assassin","Phantom Lancer","Phoenix","Primal Beast","Puck","Pudge","Pugna","Queen of Pain","Razor","Riki","Ringmaster","Rubick","Sand King","Shadow Demon","Shadow Fiend","Shadow Shaman","Silencer","Skywrath Mage","Slardar","Slark","Snapfire","Sniper","Spectre","Spirit Breaker","Storm Spirit","Sven","Techies","Templar Assassin","Terrorblade","Timbersaw","Tinker","Tiny","Treant Protector","Troll Warlord","Tusk","Underlord","Undying","Ursa","Vengeful Spirit","Venomancer","Viper","Visage","Void Spirit","Warlock","Weaver","Windranger","Winter Wyvern","Witch Doctor","Wraith King","Zeus"];
const HERO_SLUGS={"Ancient Apparition":"ancient_apparition","Anti-Mage":"antimage","Arc Warden":"arc_warden","Bounty Hunter":"bounty_hunter","Centaur Warrunner":"centaur","Chaos Knight":"chaos_knight","Crystal Maiden":"crystal_maiden","Dark Seer":"dark_seer","Dark Willow":"dark_willow","Dawnbreaker":"dawnbreaker","Death Prophet":"death_prophet","Dragon Knight":"dragon_knight","Drow Ranger":"drow_ranger","Earth Spirit":"earth_spirit","Elder Titan":"elder_titan","Ember Spirit":"ember_spirit","Faceless Void":"faceless_void","Keeper of the Light":"keeper_of_the_light","Legion Commander":"legion_commander","Lone Druid":"lone_druid","Monkey King":"monkey_king","Nature's Prophet":"furion","Night Stalker":"night_stalker","Naga Siren":"naga_siren","Necrophos":"necrolyte","Nyx Assassin":"nyx_assassin","Ogre Magi":"ogre_magi","Outworld Destroyer":"obsidian_destroyer","Phantom Assassin":"phantom_assassin","Phantom Lancer":"phantom_lancer","Primal Beast":"primal_beast","Queen of Pain":"queenofpain","Ringmaster":"ringmaster","Shadow Demon":"shadow_demon","Shadow Fiend":"nevermore","Shadow Shaman":"shadow_shaman","Skywrath Mage":"skywrath_mage","Spirit Breaker":"spirit_breaker","Storm Spirit":"storm_spirit","Templar Assassin":"templar_assassin","Terrorblade":"terrorblade","Timbersaw":"shredder","Treant Protector":"treant","Troll Warlord":"troll_warlord","Underlord":"abyssal_underlord","Vengeful Spirit":"vengefulspirit","Void Spirit":"void_spirit","Windranger":"windrunner","Winter Wyvern":"winter_wyvern","Witch Doctor":"witch_doctor","Wraith King":"skeleton_king"};
const heroImage=h=>`https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${HERO_SLUGS[h]||h.toLowerCase().replace(/[^a-z0-9]+/g,'_')}.png`;
const send=(ws,type,data={})=>ws&&ws.readyState===1&&ws.send(JSON.stringify({type,...data}));
function publicPlayers(r){return r.players.map((p,i)=>({id:p.id,name:p.name,number:i+1,host:p.id===r.hostId,connected:!!p.ws}))}
function state(r){return {players:publicPlayers(r),started:r.started,round:r.round,hostId:r.hostId,room:r.code}}
function broadcast(r,type,data={}){r.players.forEach(p=>send(p.ws,type,data))}
function makeCode(){let c;do c=crypto.randomBytes(3).toString('hex').toUpperCase();while(rooms.has(c));return c}
function startRound(r){if(r.players.length<3)return false;const spyIndex=crypto.randomInt(r.players.length),hero=HEROES[crypto.randomInt(HEROES.length)];r.started=true;r.phase='role';r.round++;r.hero=hero;r.spyId=r.players[spyIndex].id;r.players.forEach(p=>{p.role=p.id===r.spyId?'spy':'civilian';send(p.ws,'role',{role:p.role,hero:p.role==='civilian'?hero:null,image:p.role==='civilian'?heroImage(hero):null,round:r.round});});broadcast(r,'state',state(r));return true}
function removePlayer(r,p,reason='kick'){r.players=r.players.filter(x=>x!==p);if(p.ws)p.ws.close();if(r.hostId===p.id&&r.players.length){r.hostId=r.players[0].id;send(r.players[0].ws,'host',{})}if(!r.players.length)rooms.delete(r.code);else broadcast(r,'state',state(r));if(p.reconnectTimer)clearTimeout(p.reconnectTimer)}
const server=http.createServer((req,res)=>{let url=req.url.split('?')[0];if(url==='/telegram/webhook'&&req.method==='POST'&&telegram.enabled){if(telegram.WEBHOOK_SECRET&&req.headers['x-telegram-bot-api-secret-token']!==telegram.WEBHOOK_SECRET){res.writeHead(403);return res.end('Forbidden')}let body='';req.on('data',d=>body+=d);req.on('end',async()=>{try{await telegram.handleUpdate(JSON.parse(body));res.writeHead(200,{'Content-Type':'text/plain'});res.end('OK')}catch(e){console.error(e);res.writeHead(500);res.end('ERROR')}});return}let f=url==='/'?'/index.html':url,p=path.join(PUBLIC,f);if(!p.startsWith(PUBLIC)||!fs.existsSync(p)){res.writeHead(404);return res.end('Not found')}const ext=path.extname(p),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(p).pipe(res)});
const wss=new WebSocket.Server({server});
wss.on('connection',ws=>{let p=null;ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}
if(m.type==='resume'){const r=rooms.get(String(m.room||'').toUpperCase());const old=r&&r.players.find(x=>x.id===m.playerId);if(!old)return send(ws,'resumeFailed',{message:'Комната больше не существует'});if(old.reconnectTimer)clearTimeout(old.reconnectTimer);old.ws=ws;p=old;send(ws,'resumed',{code:r.code,players:publicPlayers(r),started:r.started,round:r.round,host:old.id===r.hostId});if(r.started&&old.role)send(ws,'role',{role:old.role,hero:old.role==='civilian'?r.hero:null,image:old.role==='civilian'?heroImage(r.hero):null,round:r.round});broadcast(r,'state',state(r));return}
if(m.type==='create'){const r={code:makeCode(),players:[],started:false,phase:'lobby',round:0,hero:null,spyId:null,hostId:null};p={ws,id:crypto.randomUUID(),room:r,name:String(m.name||'Игрок').trim().slice(0,24)||'Игрок',role:null,reconnectTimer:null};r.hostId=p.id;r.players.push(p);rooms.set(r.code,r);send(ws,'joined',{code:r.code,playerId:p.id,players:publicPlayers(r),host:true,started:false});return}
if(m.type==='join'){const r=rooms.get(String(m.code||'').trim().toUpperCase());if(!r)return send(ws,'error',{message:'Комната не найдена'});if(r.started)return send(ws,'error',{message:'Раунд уже начался'});if(r.players.length>=20)return send(ws,'error',{message:'Максимум 20 игроков'});p={ws,id:crypto.randomUUID(),room:r,name:String(m.name||'Игрок').trim().slice(0,24)||'Игрок',role:null,reconnectTimer:null};r.players.push(p);send(ws,'joined',{code:r.code,playerId:p.id,players:publicPlayers(r),host:p.id===r.hostId,started:false});broadcast(r,'state',state(r));return}
if(!p||!p.room)return;const r=p.room;
if(m.type==='start'||m.type==='newRound'){if(p.id!==r.hostId)return send(ws,'error',{message:'Только хост может начать раунд'});if(!startRound(r))return send(ws,'error',{message:'Нужно минимум 3 игрока'});return}
if(m.type==='kick'){if(p.id!==r.hostId)return send(ws,'error',{message:'Только хост может удалять игроков'});const target=r.players.find(x=>x.id===m.playerId);if(!target||target.id===p.id)return;send(target.ws,'kicked',{message:'Хост удалил вас из комнаты'});removePlayer(r,target);return}
});
ws.on('close',()=>{if(!p||!p.room)return;const r=p.room;p.ws=null;p.reconnectTimer=setTimeout(()=>{if(p.ws)return;removePlayer(r,p,'timeout')},RECONNECT_MS);broadcast(r,'state',state(r))})});
server.listen(PORT,async()=>{console.log('Dota Spyfall v1.3 on '+PORT);await telegram.setup()});
