const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),WebSocket=require('ws');
const PORT=process.env.PORT||3000, PUBLIC=path.join(__dirname,'public'), rooms=new Map();
const HEROES=["Abaddon", "Alchemist", "Ancient Apparition", "Anti-Mage", "Arc Warden", "Axe", "Bane", "Batrider", "Beastmaster", "Bloodseeker", "Bounty Hunter", "Brewmaster", "Bristleback", "Broodmother", "Centaur Warrunner", "Chaos Knight", "Chen", "Clinkz", "Clockwerk", "Crystal Maiden", "Dark Seer", "Dark Willow", "Dawnbreaker", "Dazzle", "Death Prophet", "Disruptor", "Doom", "Dragon Knight", "Drow Ranger", "Earthshaker", "Earth Spirit", "Elder Titan", "Ember Spirit", "Enchantress", "Enigma", "Faceless Void", "Grimstroke", "Gyrocopter", "Hoodwink", "Huskar", "Invoker", "Jakiro", "Juggernaut", "Keeper of the Light", "Kez", "Kunkka", "Legion Commander", "Leshrac", "Lich", "Lifestealer", "Lina", "Lion", "Lone Druid", "Luna", "Lycan", "Marci", "Magnus", "Mars", "Medusa", "Meepo", "Mirana", "Monkey King", "Morphling", "Muerta", "Naga Siren", "Nature's Prophet", "Necrophos", "Night Stalker", "Nyx Assassin", "Ogre Magi", "Omniknight", "Oracle", "Outworld Destroyer", "Pangolier", "Phantom Assassin", "Phantom Lancer", "Phoenix", "Primal Beast", "Puck", "Pudge", "Pugna", "Queen of Pain", "Razor", "Riki", "Ringmaster", "Rubick", "Sand King", "Shadow Demon", "Shadow Fiend", "Shadow Shaman", "Silencer", "Skywrath Mage", "Slardar", "Slark", "Snapfire", "Sniper", "Spectre", "Spirit Breaker", "Storm Spirit", "Sven", "Techies", "Templar Assassin", "Terrorblade", "Tidehunter", "Timbersaw", "Tinker", "Tiny", "Treant Protector", "Troll Warlord", "Tusk", "Underlord", "Undying", "Ursa", "Vengeful Spirit", "Venomancer", "Viper", "Visage", "Void Spirit", "Warlock", "Weaver", "Windranger", "Winter Wyvern", "Witch Doctor", "Wraith King", "Zeus"];
const send=(ws,type,data={})=>ws.readyState===1&&ws.send(JSON.stringify({type,...data}));
const broadcast=(r,type,data={})=>r.players.forEach(p=>send(p.ws,type,data));
const players=r=>r.players.map((p,i)=>({id:p.id,name:p.name,number:i+1}));
function code(){let c;do c=crypto.randomBytes(3).toString('hex').toUpperCase();while(rooms.has(c));return c;}
function start(r){if(r.players.length<3)return;const spy=crypto.randomInt(r.players.length),hero=HEROES[crypto.randomInt(HEROES.length)];r.started=true;r.round++;r.players.forEach((p,i)=>{p.role=i===spy?'spy':'civilian';send(p.ws,'role',{role:p.role,hero:p.role==='civilian'?hero:null,round:r.round})});broadcast(r,'state',{players:players(r),started:true,round:r.round});}
const server=http.createServer((req,res)=>{let f=req.url.split('?')[0];if(f==='/')f='/index.html';const p=path.join(PUBLIC,f);if(!p.startsWith(PUBLIC)||!fs.existsSync(p)){res.writeHead(404);return res.end('Not found')}const ext=path.extname(p),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(p).pipe(res);});
const wss=new WebSocket.Server({server});
wss.on('connection',ws=>{const p={ws,id:crypto.randomUUID(),room:null,name:'',role:null};
ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}
if(m.type==='create'){const c=code(),r={code:c,players:[],started:false,round:0};rooms.set(c,r);p.room=r;p.name=String(m.name||'Игрок').slice(0,24);r.players.push(p);send(ws,'joined',{code:c,players:players(r)});return}
if(m.type==='join'){const r=rooms.get(String(m.code||'').trim().toUpperCase());if(!r)return send(ws,'error',{message:'Комната не найдена'});if(r.started)return send(ws,'error',{message:'Раунд уже начался'});if(r.players.length>=20)return send(ws,'error',{message:'Максимум 20 игроков'});p.room=r;p.name=String(m.name||'Игрок').slice(0,24);r.players.push(p);send(ws,'joined',{code:r.code,players:players(r)});broadcast(r,'state',{players:players(r),started:false,round:r.round});return}
if(m.type==='start'||m.type==='newRound'){if(p.room)start(p.room);}
});
ws.on('close',()=>{const r=p.room;if(!r)return;r.players=r.players.filter(x=>x!==p);if(!r.players.length)rooms.delete(r.code);else broadcast(r,'state',{players:players(r),started:r.started,round:r.round});});
});
server.listen(PORT,()=>console.log('Dota Spyfall on '+PORT));
